spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    listener:
      missing-topics-fatal: false

kafka:
  topics:
    - name: finish-registrations
    - name: send-emails
    - name: process-payments
    - name: send-ses
    - name: credit-issued
    - name: statement-denied
server:
  port: 8081